/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { contacts } from '../Models/contactsModel';

export class contactsService {
  private static readonly dataSourceName = 'contacts';

  public static async create(record: Omit<contacts, 'contactid'>): Promise<IOperationResult<contacts>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<contacts, 'contactid'>, contacts>(
      contactsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<contacts, 'contactid'>>): Promise<IOperationResult<contacts>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<contacts, 'contactid'>>, contacts>(
      contactsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(contactsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<contacts>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<contacts>(
      contactsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<contacts[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<contacts>(
      contactsService.dataSourceName,
      options
    );
    return result;
  }
}
